"""add field UserAccessRights

Revision ID: 6043b89ca3cf
Revises: e72693bec7a6
Create Date: 2025-06-13 09:45:51.239805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6043b89ca3cf'
down_revision: Union[str, None] = 'e72693bec7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


UserAccessRights = postgresql.ENUM(
    'DEFAULT',
    'PLUS',
    'PRO',
    'FULL',
    'OWNER',
    name='user_access_rights',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        CREATE TYPE user_access_rights 
        AS ENUM ('DEFAULT', 'PLUS', 'PRO', 'FULL', 'OWNER')
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_rights', UserAccessRights, nullable=False, server_default='DEFAULT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_rights')
    # ### end Alembic commands ###

    op.execute("""
        DROP TYPE IF EXISTS user_access_rights
    """)
