"""created access_permissions table in db

Revision ID: 229b12c442c2
Revises: 6043b89ca3cf
Create Date: 2025-06-14 12:27:48.722870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '229b12c442c2'
down_revision: Union[str, None] = '6043b89ca3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    UserAccessRights = sa.Enum(
        name='user_access_rights',
        metadata=sa.MetaData(),
        schema='public'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('access_rights', UserAccessRights, nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_permissions_user_id'), 'access_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_permissions_user_id'), table_name='access_permissions')
    op.drop_table('access_permissions')
    # ### end Alembic commands ###
