"""add device_id field to user model

Revision ID: 8459fdd91424
Revises: 50bb983100d5
Create Date: 2025-12-18 21:57:28.604538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8459fdd91424'
down_revision: Union[str, None] = '50bb983100d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users",
    sa.Column("device_id", sa.String(16), nullable=True, unique=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "device_id")
    # ### end Alembic commands ###
