"""initial

Revision ID: e72693bec7a6
Revises: 
Create Date: 2025-05-17 21:18:52.974520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e72693bec7a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


StationStatusType = postgresql.ENUM(
    'NOT_VERIFIED',
    'NOT_WORK',
    'WORKS',
    name='station_status_type',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        CREATE TYPE station_status_type 
        AS ENUM ('NOT_VERIFIED', 'NOT_WORK', 'WORKS')
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('status', StationStatusType, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_stations_status'), 'stations', ['status'], unique=False)
    op.create_index('ix_tags_gin', 'stations', ['tags'], unique=False, postgresql_using='gin')

    op.create_table('users',
    sa.Column('uuid_id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=21), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('uuid_id')
    )

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'station_id')
    )

    op.execute(sa.schema.CreateSequence(sa.Sequence('favorites_id_seq')))
    op.alter_column('favorites', 'id', server_default=sa.text("nextval('favorites_id_seq')"))
    op.execute(sa.text("SELECT setval('favorites_id_seq', COALESCE((SELECT MAX(id) FROM favorites), 1))"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'id', server_default=None)
    op.execute(sa.schema.DropSequence(sa.Sequence('favorites_id_seq')))

    op.drop_table('favorites')
    op.drop_table('users')
    op.drop_index('ix_tags_gin', table_name='stations', postgresql_using='gin')
    op.drop_index(op.f('ix_stations_status'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###

    op.execute("""
        DROP TYPE IF EXISTS station_status_type
    """)
