x-default-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  db:
    <<: *default-logging
    image: postgres
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.2'
    env_file: .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    <<: *default-logging
    image: radio-collection-service-api
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
    env_file: .env
    command: ["--workers", "1"]
    volumes:
      - ./backend/src/migration/versions:/app/migration/versions
      - ./backend/src/templates:/app/templates
      - ./shared_data:/app/data
    user: "1000:1000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    <<: *default-logging
    image: radio-collection-service-web
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.2'
    env_file: .env
    volumes:
      - ./frontend/src:/app/web/src
      - /app/web/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    <<: *default-logging
    image: radio-collection-service-api
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    env_file: .env
    entrypoint: ["python", "-m"]
    command: "workers.worker"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./shared_data:/app/data

  caddy:
    image: caddy:alpine
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
