server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            log: log
      - drop:
          expression: ".*(GET|HEAD) /api/health.*"
          expression: ".*start worker process.*"
          expression: ".*worker process.*"
          expression: ".*GET / HTTP/1.1.*"
          expression: ".*client 127.0.0.1 closed keepalive connection.*"
