services:
  - type: psql
    name: db
    plan: free
    databaseName: ${POSTGRES_DB_NAME:-mydatabase}
    user: ${POSTGRES_USERNAME:-myuser}

  - type: redis
    name: redis
    plan: free

  - type: web
    name: api
    env: python
    plan: free
    buildCommand:
    context: ./backend
    dockerfile: Dockerfile
    startCommand: uvicorn main:app --lifespan on --host 0.0.0.0 --port $PORT --workers 4
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          property: connectionString
      - key: FASTAPI_TITLE
        value: Radio Collection Service API
      - key: FASTAPI_DESCRIPTION
        value: API for radio collections service
      - key: FASTAPI_VERSION
        value: 1.0.0
      - key: RESOLVER_PLUS
        value: 30
      - key: RESOLVER_PRO
        value: 30
      - key: RESOLVER_FULL
        value: 30
      - key: ADMIN_TITLE
        value: Radio Collection Service Admin App
      - key: ADMIN_BASE_URL
        value: /admin
      - key: ADMIN_TEMPLATES_DIR
        value: templates

  - type: worker
    name: worker
    env: python
    plan: free
    buildCommand:
    context: ./backend
    dockerfile: Dockerfile
    startCommand: python -m workers.worker
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          property: connectionString
      - key: PARSER_MAX_WORKERS
        value: 4
      - key: PARSER_BATCH_SIZE
        value: 3000
      - key: PARSER_DEFAULT_SLEEP_TIMEOUT
        value: 0.5
      - key: WORKER_REDIS_DATABASE
        value: 0
      - key: WORKER_HANDLE_SIGNALS
        value: false
      - key: WORKER_HEALTH_CHECK_INTERVAL
        value: 60
      - key: WORKER_MAX_JOBS
        value: 10
      - key: WORKER_JOB_TIMEOUT
        value: 600
      - key: TESTER_CHECKER_TYPE
        value: vlc
      - key: TESTER_REPEAT_COUNT
        value: 3
      - key: TESTER_REPEAT_TIMEOUT
        value: 1
      - key: TESTER_MAX_CONCURRENT_TASKS
        value: 20
      - key: TESTER_BATCH_SIZE
        value: 1000
      - key: TESTER_BATCH_LIMIT
        value: 2000
      - key: TESTER_QUEUE_TIMEOUT
        value: 1.0
      - key: TESTER_UPDATE_TIMEOUT
        value: 0.1

  - type: static_site
    name: web
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: api
          property: internalUrl
